### ISSUE TITLE
Online Certification - IE

### ISSUE THREAD

**Issue by kbt1** [stellaballa/AERAEDU#44]
I had a member call saying he is getting a white screen when he logs in on the Online Certification Website.
I finally figured out he is using Internet Explorer so I logged in with IE version 11 and got the same white screen. 
Other then a different browser, is there is a reason for this? Update IE? Just checking.

From the member with the issue: thin client computers won't accept google chrome

**Comment by stellaballa** [comment]
@kbt1  we will look into this.

**Comment by SagarPC** [comment]
@kbt1 We used Ember Js Framework 1.10 to build the Aera Edu program. It's a completely javascript-based framework as many things related to javascript not supported in IE. Instead of IE, we can ask the client to use "Microsoft Edge". It's Microsoft Recommended browser. 

![image](https://user-images.githubusercontent.com/31076567/67357321-90765480-f57a-11e9-90b0-7c30cee0bd8b.png)

**Comment by stellaballa** [comment]
Sagar, Karen is asking about the online training not prosispro, I just want
to make sure your answer is for online training.

**Comment by SagarPC** [comment]
@stellaballa Yes, my answer is for Online training.

**Comment by stellaballa** [comment]
@kbt1 online training never worked on IE, the member can use chrome, safari and edge.

**Comment by kbt1** [comment]
he got in, thank you!
